---
# tasks file for nbde_server.

- name: Set version-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Include the appropriate provider tasks
  include_tasks: "main-{{ nbde_server_provider }}.yml"

# vim:set ts=2 sw=2 et:
